---
kind: pipeline
type: docker
name: BUILD-TEST

steps:
  - name: Builder
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5
      - docker build --progress=plain -f builder.dockerfile -t alcapone1933/composerize:builder .
      - rm -fv composerize.tar.gz
      - docker create --name builder alcapone1933/composerize:builder
      - docker cp builder:/opt/composerize.tar.gz ./composerize.tar.gz
      - docker build --progress=plain -f builder-single.dockerfile --target composerize -t alcapone1933/composerize:composerize .
      - docker build --progress=plain -f builder-single.dockerfile --target decomposerize -t alcapone1933/composerize:decomposerize .
      - docker build --progress=plain -f builder-single.dockerfile --target composeverter -t alcapone1933/composerize:composeverter .
      - docker rm -vf builder
      - git add composerize.tar.gz && git commit -m "composerize.tar.gz"
  - name: Build Multi-arch
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
      repo: alcapone1933/composerize
      auto_tag: true
      # tags: latest
      dry_run: true

services:
  - name: docker
    image: alcapone1933/docker-dind:latest
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
  - master
  event:
  - push
  - pull_request
  - custom

---
kind: pipeline
type: docker
name: BUILD-Dockerhub

steps:
  - name: Builder
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:    
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin      
      - docker build --progress=plain -f builder.dockerfile -t alcapone1933/composerize:builder --push .
      - rm -fv composerize.tar.gz
      - docker create --name builder alcapone1933/composerize:builder
      - docker cp builder:/opt/composerize.tar.gz ./composerize.tar.gz
      - docker build --progress=plain -f builder-single.dockerfile --target composerize -t alcapone1933/composerize:composerize --push .
      - docker build --progress=plain -f builder-single.dockerfile --target decomposerize -t alcapone1933/composerize:decomposerize --push .
      - docker build --progress=plain -f builder-single.dockerfile --target composeverter -t alcapone1933/composerize:composeverter --push .
      - docker rm -vf builder
      - git add composerize.tar.gz && git commit -m "composerize.tar.gz"
  - name: Build Multi-arch Dockerhub
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password: 
        from_secret: DOCKER_PASS    
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
      repo: alcapone1933/composerize
      auto_tag: true
      # tags: latest
  - name: Build Multi-arch Dockerhub Version
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password: 
        from_secret: DOCKER_PASS    
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
      repo: alcapone1933/composerize
      # tags: latest
      auto_tag: true
      auto_tag_suffix: v1.6.7

services:
  - name: docker
    image: alcapone1933/docker-dind:latest
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
volumes:
  - name: dockersock
    temp: {}
  
trigger:
#  ref:
#    - refs/heads/master
#    - refs/tags/**
#    - refs/pull/**
  branch:
  - master
  event:
  - custom

depends_on:
  - BUILD-TEST
